/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.so.alw.futterbaulinie;

import org.gdal.gdal.Band;
import org.gdal.gdal.Dataset;
import org.gdal.gdal.gdal;
import org.gdal.gdalconst.gdalconstJNI;

public class App {

    public static void main(String[] args) {
        
        gdal.AllRegister();
        gdal.UseExceptions();
        
        System.out.println("Running against GDAL " + gdal.VersionInfo());


        Dataset hDataset = gdal.Open("/vagrant/data/2594500_1230000_vegetation.tif", gdalconstJNI.GA_ReadOnly_get());
        Band band = hDataset.GetRasterBand(1);
        
        int xsize = band.getXSize();
        int ysize = band.getYSize();
        
        byte[] byteArray = new byte[xsize * ysize];
        byte[] byteArray2 = new byte[xsize * ysize];

        band.ReadRaster(0, 0, xsize, ysize, gdalconstJNI.GDT_Byte_get(), byteArray);


        for (int j=0; j < ysize; j++) {
            for (int i=0; i < xsize; i++) {
                byte bVal = byteArray[j*xsize+i]; 

                byteArray2[j*xsize+i] = bVal;

                //System.out.println(bVal);
            }
        }
        
        band2.WriteRaster(0, 0, xsize, ysize, gdalconstJNI.GDT_Byte_get(), byteArray2);

        
        System.out.println(hDataset.GetDescription());
        System.out.println("Hallo Welt.");
//        
//        System.exit(0);
    }
}
